name: Benedikt

on:
  workflow_dispatch:
  pull_request:

jobs:
  diktat_check:
    name: 'diKTat Check'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: nulls/benedikt@ebd0cf61265705b839874408ff79ae2764d67f10
        with:
          reporter: 'checkstyle'
          debug: true
          input-paths: |
            examples/**/*.kt
