name: Benedikt

on:
  workflow_dispatch:

jobs:
  diktat_check:
    name: 'diKTat Check'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: nulls/benedikt@b3fda2282cf956da8811da3c760532c2c079f138
        with:
          input-paths: |
            examples/**/*.kt
