name: Benedikt

on:
  workflow_dispatch:

jobs:
  diktat_check:
    name: 'diKTat Check'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: nulls/benedikt@5c2b431b3a7a567d9103b917fcf520f78e2cc899
        with:
          input-paths: |
            examples/**/*.kt
